{{- if and .Values.multicluster.enabled .Values.multicluster.clusterGateway.secureTLS.enabled (not .Values.multicluster.clusterGateway.secureTLS.certManager.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubevela.fullname" . }}-cluster-gateway-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "kubevela.name" . }}-cluster-gateway-admission
    {{- include "kubevela.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubevela.fullname" . }}-cluster-gateway-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "kubevela.name" . }}-cluster-gateway-admission
    {{- include "kubevela.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubevela.fullname" . }}-cluster-gateway-admission
subjects:
  - kind: ServiceAccount
    name: {{ template "kubevela.fullname" . }}-cluster-gateway-admission
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubevela.fullname" . }}-cluster-gateway-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "kubevela.name" . }}-cluster-gateway-admission
    {{- include "kubevela.labels" . | nindent 4 }}
---
{{ if not .Values.deployByPod }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  {{ include "kubevela-cluster-gateway-tls-secret-create.annotations" . | indent 2 }}
  {{ include "kubevela-cluster-gateway-tls-secret-create.name-labels" . | indent 2 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
    {{ include "kubevela-cluster-gateway-tls-secret-create.name-labels" . | indent 6 }}
    spec:
  {{ include "kubevela-cluster-gateway-tls-secret-create.podSpec" . | indent 6}}
{{ end }}
---
{{ if not .Values.deployByPod }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  {{ include "kubevela-cluster-gateway-tls-secret-patch.name-labels" . | indent 2 }}
  {{ include "kubevela-cluster-gateway-tls-secret-patch.annotations" . | indent 2 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
    {{ include "kubevela-cluster-gateway-tls-secret-patch.name-labels" . | indent 6 }}
    spec:
  {{ include "kubevela-cluster-gateway-tls-secret-patch.podSpec" . | indent 6}}
  {{ end }}
{{ end }}